// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionEntryDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // debit | credit
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	IsFee         bool                   `protobuf:"varint,5,opt,name=is_fee,json=isFee,proto3" json:"is_fee,omitempty"`
	IsInitial     bool                   `protobuf:"varint,6,opt,name=is_initial,json=isInitial,proto3" json:"is_initial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEntryDto) Reset() {
	*x = TransactionEntryDto{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEntryDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEntryDto) ProtoMessage() {}

func (x *TransactionEntryDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEntryDto.ProtoReflect.Descriptor instead.
func (*TransactionEntryDto) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEntryDto) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *TransactionEntryDto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TransactionEntryDto) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionEntryDto) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *TransactionEntryDto) GetIsFee() bool {
	if x != nil {
		return x.IsFee
	}
	return false
}

func (x *TransactionEntryDto) GetIsInitial() bool {
	if x != nil {
		return x.IsInitial
	}
	return false
}

type InitiateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // transfer|deposit|withdrawal|payment|reversal|adjustment
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,3,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Fee           float64                `protobuf:"fixed64,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Purpose       *string                `protobuf:"bytes,8,opt,name=purpose,proto3,oneof" json:"purpose,omitempty"`
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Transfers     []*TransactionEntryDto `protobuf:"bytes,10,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateTransactionRequest) Reset() {
	*x = InitiateTransactionRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransactionRequest) ProtoMessage() {}

func (x *InitiateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransactionRequest.ProtoReflect.Descriptor instead.
func (*InitiateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitiateTransactionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InitiateTransactionRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *InitiateTransactionRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *InitiateTransactionRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InitiateTransactionRequest) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *InitiateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiateTransactionRequest) GetPurpose() string {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return ""
}

func (x *InitiateTransactionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *InitiateTransactionRequest) GetTransfers() []*TransactionEntryDto {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type InitiateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *string                `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	ProviderRef   *string                `protobuf:"bytes,2,opt,name=provider_ref,json=providerRef,proto3,oneof" json:"provider_ref,omitempty"`
	Rrn           string                 `protobuf:"bytes,3,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Narration     string                 `protobuf:"bytes,6,opt,name=narration,proto3" json:"narration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateTransactionResponse) Reset() {
	*x = InitiateTransactionResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransactionResponse) ProtoMessage() {}

func (x *InitiateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransactionResponse.ProtoReflect.Descriptor instead.
func (*InitiateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateTransactionResponse) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *InitiateTransactionResponse) GetProviderRef() string {
	if x != nil && x.ProviderRef != nil {
		return *x.ProviderRef
	}
	return ""
}

func (x *InitiateTransactionResponse) GetRrn() string {
	if x != nil {
		return x.Rrn
	}
	return ""
}

func (x *InitiateTransactionResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitiateTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InitiateTransactionResponse) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

var File_proto_transaction_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"#proto/transaction/transaction.proto\x12\vtransaction\"\xb2\x01\n" +
	"\x13TransactionEntryDto\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x15\n" +
	"\x06is_fee\x18\x05 \x01(\bR\x05isFee\x12\x1d\n" +
	"\n" +
	"is_initial\x18\x06 \x01(\bR\tisInitial\"\x84\x03\n" +
	"\x1aInitiateTransactionRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fprovider_ref\x18\x03 \x01(\tR\vproviderRef\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x01R\x03fee\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1d\n" +
	"\apurpose\x18\b \x01(\tH\x00R\apurpose\x88\x01\x01\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x01R\vdescription\x88\x01\x01\x12>\n" +
	"\ttransfers\x18\n" +
	" \x03(\v2 .transaction.TransactionEntryDtoR\ttransfersB\n" +
	"\n" +
	"\b_purposeB\x0e\n" +
	"\f_description\"\xdf\x01\n" +
	"\x1bInitiateTransactionResponse\x12\x1e\n" +
	"\border_id\x18\x01 \x01(\tH\x00R\aorderId\x88\x01\x01\x12&\n" +
	"\fprovider_ref\x18\x02 \x01(\tH\x01R\vproviderRef\x88\x01\x01\x12\x10\n" +
	"\x03rrn\x18\x03 \x01(\tR\x03rrn\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tnarration\x18\x06 \x01(\tR\tnarrationB\v\n" +
	"\t_order_idB\x0f\n" +
	"\r_provider_ref2s\n" +
	"\x12TransactionService\x12]\n" +
	"\bInitiate\x12'.transaction.InitiateTransactionRequest\x1a(.transaction.InitiateTransactionResponseB,Z*github.com/katuva/wallet/proto/transactionb\x06proto3"

var (
	file_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_proto_rawDescData []byte
)

func file_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_transaction_proto_rawDescData
}

var file_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transaction_transaction_proto_goTypes = []any{
	(*TransactionEntryDto)(nil),         // 0: transaction.TransactionEntryDto
	(*InitiateTransactionRequest)(nil),  // 1: transaction.InitiateTransactionRequest
	(*InitiateTransactionResponse)(nil), // 2: transaction.InitiateTransactionResponse
}
var file_proto_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.InitiateTransactionRequest.transfers:type_name -> transaction.TransactionEntryDto
	1, // 1: transaction.TransactionService.Initiate:input_type -> transaction.InitiateTransactionRequest
	2, // 2: transaction.TransactionService.Initiate:output_type -> transaction.InitiateTransactionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_proto_init() }
func file_proto_transaction_transaction_proto_init() {
	if File_proto_transaction_transaction_proto != nil {
		return
	}
	file_proto_transaction_transaction_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_transaction_transaction_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_proto = out.File
	file_proto_transaction_transaction_proto_goTypes = nil
	file_proto_transaction_transaction_proto_depIdxs = nil
}
