syntax = "proto3";

package wallet;
option go_package = "github.com/katuva/wallet/proto/wallet";

service WalletService {
  rpc Create(CreateWalletRequest) returns (CreateWalletResponse);
}

message CreateWalletRequest {
  string profile_id  = 1;
  string merchant_id = 2;
  string currency    = 3;
}

message ProfileDto {
  string id        = 1;
  string full_name = 2;
}

message CreateWalletResponse {
  string     id                 = 1;
  string     created_at         = 2;
  string     updated_at         = 3;
  string     number             = 4;
  string     status             = 5;
  string     currency           = 6;
  double     available_balance  = 7;
  double     processing_balance = 8;
  double     actual_balance     = 9;
  int64      version            = 10;
  ProfileDto profile            = 11;
  ProfileDto merchant           = 12;
}