// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/wallet/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_proto_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *CreateWalletRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ProfileDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileDto) Reset() {
	*x = ProfileDto{}
	mi := &file_proto_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDto) ProtoMessage() {}

func (x *ProfileDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDto.ProtoReflect.Descriptor instead.
func (*ProfileDto) Descriptor() ([]byte, []int) {
	return file_proto_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileDto) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateWalletResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Number            string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AvailableBalance  float64                `protobuf:"fixed64,7,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	ProcessingBalance float64                `protobuf:"fixed64,8,opt,name=processing_balance,json=processingBalance,proto3" json:"processing_balance,omitempty"`
	ActualBalance     float64                `protobuf:"fixed64,9,opt,name=actual_balance,json=actualBalance,proto3" json:"actual_balance,omitempty"`
	Version           int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	Profile           *ProfileDto            `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	Merchant          *ProfileDto            `protobuf:"bytes,12,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_proto_wallet_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWalletResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateWalletResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateWalletResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateWalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateWalletResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateWalletResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CreateWalletResponse) GetProcessingBalance() float64 {
	if x != nil {
		return x.ProcessingBalance
	}
	return 0
}

func (x *CreateWalletResponse) GetActualBalance() float64 {
	if x != nil {
		return x.ActualBalance
	}
	return 0
}

func (x *CreateWalletResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateWalletResponse) GetProfile() *ProfileDto {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *CreateWalletResponse) GetMerchant() *ProfileDto {
	if x != nil {
		return x.Merchant
	}
	return nil
}

var File_proto_wallet_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"\x19proto/wallet/wallet.proto\x12\x06wallet\"q\n" +
	"\x13CreateWalletRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"9\n" +
	"\n" +
	"ProfileDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"\xab\x03\n" +
	"\x14CreateWalletResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12+\n" +
	"\x11available_balance\x18\a \x01(\x01R\x10availableBalance\x12-\n" +
	"\x12processing_balance\x18\b \x01(\x01R\x11processingBalance\x12%\n" +
	"\x0eactual_balance\x18\t \x01(\x01R\ractualBalance\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x12,\n" +
	"\aprofile\x18\v \x01(\v2\x12.wallet.ProfileDtoR\aprofile\x12.\n" +
	"\bmerchant\x18\f \x01(\v2\x12.wallet.ProfileDtoR\bmerchant2T\n" +
	"\rWalletService\x12C\n" +
	"\x06Create\x12\x1b.wallet.CreateWalletRequest\x1a\x1c.wallet.CreateWalletResponseB'Z%github.com/katuva/wallet/proto/walletb\x06proto3"

var (
	file_proto_wallet_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_wallet_proto_rawDescData []byte
)

func file_proto_wallet_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_wallet_proto_rawDesc), len(file_proto_wallet_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_wallet_proto_rawDescData
}

var file_proto_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wallet_wallet_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),  // 0: wallet.CreateWalletRequest
	(*ProfileDto)(nil),           // 1: wallet.ProfileDto
	(*CreateWalletResponse)(nil), // 2: wallet.CreateWalletResponse
}
var file_proto_wallet_wallet_proto_depIdxs = []int32{
	1, // 0: wallet.CreateWalletResponse.profile:type_name -> wallet.ProfileDto
	1, // 1: wallet.CreateWalletResponse.merchant:type_name -> wallet.ProfileDto
	0, // 2: wallet.WalletService.Create:input_type -> wallet.CreateWalletRequest
	2, // 3: wallet.WalletService.Create:output_type -> wallet.CreateWalletResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_wallet_wallet_proto_init() }
func file_proto_wallet_wallet_proto_init() {
	if File_proto_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_wallet_proto_rawDesc), len(file_proto_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_wallet_proto = out.File
	file_proto_wallet_wallet_proto_goTypes = nil
	file_proto_wallet_wallet_proto_depIdxs = nil
}
