// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: actors/actors.proto

package actors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Action         string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // debit | credit
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose        string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Set once a reversal has been issued for this leg; persisted so a
	// recovered transaction resumes the reversal under the same key.
	ReversalKey   string `protobuf:"bytes,6,opt,name=reversal_key,json=reversalKey,proto3" json:"reversal_key,omitempty"`
	IsFee         bool   `protobuf:"varint,7,opt,name=is_fee,json=isFee,proto3" json:"is_fee,omitempty"`
	IsInitial     bool   `protobuf:"varint,8,opt,name=is_initial,json=isInitial,proto3" json:"is_initial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferEntry) Reset() {
	*x = TransferEntry{}
	mi := &file_actors_actors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEntry) ProtoMessage() {}

func (x *TransferEntry) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEntry.ProtoReflect.Descriptor instead.
func (*TransferEntry) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{0}
}

func (x *TransferEntry) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *TransferEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TransferEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferEntry) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *TransferEntry) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferEntry) GetReversalKey() string {
	if x != nil {
		return x.ReversalKey
	}
	return ""
}

func (x *TransferEntry) GetIsFee() bool {
	if x != nil {
		return x.IsFee
	}
	return false
}

func (x *TransferEntry) GetIsInitial() bool {
	if x != nil {
		return x.IsInitial
	}
	return false
}

// Sent by the service layer once the transaction row is persisted as pending,
// or by the recovery manager to re-drive a transaction whose orchestrator was
// lost (resume = true; the actor reconstructs progress from the ledger).
type StartTransactionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // used for partition pruning
	Transfers     []*TransferEntry       `protobuf:"bytes,3,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Resume        bool                   `protobuf:"varint,4,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTransactionMsg) Reset() {
	*x = StartTransactionMsg{}
	mi := &file_actors_actors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTransactionMsg) ProtoMessage() {}

func (x *StartTransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTransactionMsg.ProtoReflect.Descriptor instead.
func (*StartTransactionMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{1}
}

func (x *StartTransactionMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StartTransactionMsg) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *StartTransactionMsg) GetTransfers() []*TransferEntry {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *StartTransactionMsg) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

type CreditWalletMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose        string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	TransactionId  string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreditWalletMsg) Reset() {
	*x = CreditWalletMsg{}
	mi := &file_actors_actors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditWalletMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditWalletMsg) ProtoMessage() {}

func (x *CreditWalletMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditWalletMsg.ProtoReflect.Descriptor instead.
func (*CreditWalletMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{2}
}

func (x *CreditWalletMsg) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreditWalletMsg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditWalletMsg) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CreditWalletMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreditWalletMsg) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DebitWalletMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose        string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	TransactionId  string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DebitWalletMsg) Reset() {
	*x = DebitWalletMsg{}
	mi := &file_actors_actors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitWalletMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitWalletMsg) ProtoMessage() {}

func (x *DebitWalletMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitWalletMsg.ProtoReflect.Descriptor instead.
func (*DebitWalletMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{3}
}

func (x *DebitWalletMsg) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DebitWalletMsg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitWalletMsg) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DebitWalletMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DebitWalletMsg) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// Reply from a WalletActor. An empty error_code means success.
type WalletResultMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	WalletId       string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	InitialBalance int64                  `protobuf:"varint,4,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	UpdatedBalance int64                  `protobuf:"varint,5,opt,name=updated_balance,json=updatedBalance,proto3" json:"updated_balance,omitempty"`
	Amount         int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WalletResultMsg) Reset() {
	*x = WalletResultMsg{}
	mi := &file_actors_actors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResultMsg) ProtoMessage() {}

func (x *WalletResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResultMsg.ProtoReflect.Descriptor instead.
func (*WalletResultMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{4}
}

func (x *WalletResultMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *WalletResultMsg) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletResultMsg) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WalletResultMsg) GetInitialBalance() int64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *WalletResultMsg) GetUpdatedBalance() int64 {
	if x != nil {
		return x.UpdatedBalance
	}
	return 0
}

func (x *WalletResultMsg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletResultMsg) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *WalletResultMsg) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Self-message: all wallet replies (and reversals) collected, write final status.
type FinalizeTransactionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTransactionMsg) Reset() {
	*x = FinalizeTransactionMsg{}
	mi := &file_actors_actors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTransactionMsg) ProtoMessage() {}

func (x *FinalizeTransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTransactionMsg.ProtoReflect.Descriptor instead.
func (*FinalizeTransactionMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizeTransactionMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// Self-message: legs still awaiting a reply are treated as failed.
type TransactionTimeoutMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Stage         int32                  `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"` // the stage the timer was armed in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionTimeoutMsg) Reset() {
	*x = TransactionTimeoutMsg{}
	mi := &file_actors_actors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTimeoutMsg) ProtoMessage() {}

func (x *TransactionTimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_actors_actors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTimeoutMsg.ProtoReflect.Descriptor instead.
func (*TransactionTimeoutMsg) Descriptor() ([]byte, []int) {
	return file_actors_actors_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionTimeoutMsg) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionTimeoutMsg) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

var File_actors_actors_proto protoreflect.FileDescriptor

const file_actors_actors_proto_rawDesc = "" +
	"\n" +
	"\x13actors/actors.proto\x12\x06actors\"\xf8\x01\n" +
	"\rTransferEntry\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\freversal_key\x18\x06 \x01(\tR\vreversalKey\x12\x15\n" +
	"\x06is_fee\x18\a \x01(\bR\x05isFee\x12\x1d\n" +
	"\n" +
	"is_initial\x18\b \x01(\bR\tisInitial\"\xb1\x01\n" +
	"\x13StartTransactionMsg\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\x123\n" +
	"\ttransfers\x18\x03 \x03(\v2\x15.actors.TransferEntryR\ttransfers\x12\x16\n" +
	"\x06resume\x18\x04 \x01(\bR\x06resume\"\xb0\x01\n" +
	"\x0fCreditWalletMsg\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xaf\x01\n" +
	"\x0eDebitWalletMsg\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xac\x02\n" +
	"\x0fWalletResultMsg\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0finitial_balance\x18\x04 \x01(\x03R\x0einitialBalance\x12'\n" +
	"\x0fupdated_balance\x18\x05 \x01(\x03R\x0eupdatedBalance\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"?\n" +
	"\x16FinalizeTransactionMsg\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"T\n" +
	"\x15TransactionTimeoutMsg\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\x05R\x05stageB'Z%github.com/katuva/wallet/proto/actorsb\x06proto3"

var (
	file_actors_actors_proto_rawDescOnce sync.Once
	file_actors_actors_proto_rawDescData []byte
)

func file_actors_actors_proto_rawDescGZIP() []byte {
	file_actors_actors_proto_rawDescOnce.Do(func() {
		file_actors_actors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actors_actors_proto_rawDesc), len(file_actors_actors_proto_rawDesc)))
	})
	return file_actors_actors_proto_rawDescData
}

var file_actors_actors_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_actors_actors_proto_goTypes = []any{
	(*TransferEntry)(nil),          // 0: actors.TransferEntry
	(*StartTransactionMsg)(nil),    // 1: actors.StartTransactionMsg
	(*CreditWalletMsg)(nil),        // 2: actors.CreditWalletMsg
	(*DebitWalletMsg)(nil),         // 3: actors.DebitWalletMsg
	(*WalletResultMsg)(nil),        // 4: actors.WalletResultMsg
	(*FinalizeTransactionMsg)(nil), // 5: actors.FinalizeTransactionMsg
	(*TransactionTimeoutMsg)(nil),  // 6: actors.TransactionTimeoutMsg
}
var file_actors_actors_proto_depIdxs = []int32{
	0, // 0: actors.StartTransactionMsg.transfers:type_name -> actors.TransferEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_actors_actors_proto_init() }
func file_actors_actors_proto_init() {
	if File_actors_actors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actors_actors_proto_rawDesc), len(file_actors_actors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actors_actors_proto_goTypes,
		DependencyIndexes: file_actors_actors_proto_depIdxs,
		MessageInfos:      file_actors_actors_proto_msgTypes,
	}.Build()
	File_actors_actors_proto = out.File
	file_actors_actors_proto_goTypes = nil
	file_actors_actors_proto_depIdxs = nil
}
